---
- hosts: vagrant_test
  roles:
  - { role: test,            tags: ['yay'] }
  #- { role: base,            tags: ['base'] }
  #- { role: users,           tags: ['users', 'never'] }
  #- { role: printers,        tags: ['printers'] }
  #- { role: browsers,        tags: ['browsers'] }
  #- { role: developer-tools, tags: ['dev-tools'] }
  #- { role: devops-tools,    tags: ['devops-tools'] }
  #- { role: kubernetes-tools,    tags: ['kubernetes-tools'] }
  #- { role: editors,         tags: ['editors'] }
  #- { role: media,           tags: ['media'] }
  #- { role: gnome,           tags: ['gnome'] }

