---
- name: Install Utils from Arch User Repository
  yay:
    name: '{{ utils_aur }}'
    state: present
  become: yes
  tags:
    - aur


- name: Install media packages
  pacman:
    name: '{{ media }}'
    state: present
  become: yes
